Document: cuimhne-sox
Title: Debian cuimhne-sox Manual
Author: <insert document author here>
Abstract: This manual describes what cuimhne-sox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cuimhne-sox/cuimhne-sox.sgml.gz

Format: postscript
Files: /usr/share/doc/cuimhne-sox/cuimhne-sox.ps.gz

Format: text
Files: /usr/share/doc/cuimhne-sox/cuimhne-sox.text.gz

Format: HTML
Index: /usr/share/doc/cuimhne-sox/html/index.html
Files: /usr/share/doc/cuimhne-sox/html/*.html
