Document: jack-capture
Title: Debian jack-capture Manual
Author: <insert document author here>
Abstract: This manual describes what jack-capture is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jack-capture/jack-capture.sgml.gz

Format: postscript
Files: /usr/share/doc/jack-capture/jack-capture.ps.gz

Format: text
Files: /usr/share/doc/jack-capture/jack-capture.text.gz

Format: HTML
Index: /usr/share/doc/jack-capture/html/index.html
Files: /usr/share/doc/jack-capture/html/*.html
